name: MS Graph API Keep-Alive

on:
  schedule:
    # It runs every 7 hours (adjustable).
    - cron: "0 */7 * * *"
  workflow_dispatch:
  watch:
    types: [started]

jobs:
  api-call:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run API Script
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        run: |
          python main.py

      - name: Update Refresh Token in Secrets
        if: hashFiles('new_token.txt') != ''
        run: |
          NEW_TOKEN=$(cat new_token.txt)

          echo "Updating REFRESH_TOKEN in the repository..."
          echo "$NEW_TOKEN" | gh secret set REFRESH_TOKEN --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Clean up sensitive files
        if: always()
        run: |
          rm -f new_token.txt

      - name: Commit log
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.USER }}
          git add time.log
          git commit -m "Update log: $(date +'%Y-%m-%d %H:%M')" --allow-empty
          git push
